name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Create static site
        shell: bash
        run: |
          # Copy the public directory as is to _site (preserve all subdirectories)
          cp -r public _site
          
          # Add .nojekyll file to bypass Jekyll processing
          touch _site/.nojekyll
          
          # Make sure we have the necessary folders and files
          mkdir -p _site/MelVocalcoachingbBerlin
          mkdir -p _site/MelVocalcoachingbBerlin/MelVocalcoachingbBerlin
          
          # Ensure index.html files exist in all locations
          if [ ! -f "_site/index.html" ]; then
            cp _site/MelVocalcoachingbBerlin/index.html _site/index.html
          fi
          
          # Simple approach to avoid heredoc issues
          if [ ! -f "_site/index.html" ]; then
            echo '<!DOCTYPE html>' > _site/index.html
            echo '<html>' >> _site/index.html
            echo '  <head>' >> _site/index.html
            echo '    <meta charset="UTF-8">' >> _site/index.html
            echo '    <meta http-equiv="refresh" content="0;url=/MelVocalcoachingbBerlin/">' >> _site/index.html
            echo '    <title>Redirecting to Mel Vocal Coaching Berlin</title>' >> _site/index.html
            echo '  </head>' >> _site/index.html
            echo '  <body>' >> _site/index.html
            echo '    <p>Redirecting to <a href="/MelVocalcoachingbBerlin/">Mel Vocal Coaching Berlin</a>...</p>' >> _site/index.html
            echo '  </body>' >> _site/index.html
            echo '</html>' >> _site/index.html
          fi
          
          # Create the necessary redirect file
          if [ ! -f "_site/MelVocalcoachingbBerlin/MelVocalcoachingbBerlin/index.html" ]; then
            echo '<!DOCTYPE html>' > _site/MelVocalcoachingbBerlin/MelVocalcoachingbBerlin/index.html
            echo '<html>' >> _site/MelVocalcoachingbBerlin/MelVocalcoachingbBerlin/index.html
            echo '  <head>' >> _site/MelVocalcoachingbBerlin/MelVocalcoachingbBerlin/index.html
            echo '    <meta charset="UTF-8">' >> _site/MelVocalcoachingbBerlin/MelVocalcoachingbBerlin/index.html
            echo '    <meta http-equiv="refresh" content="0;url=/MelVocalcoachingbBerlin/">' >> _site/MelVocalcoachingbBerlin/MelVocalcoachingbBerlin/index.html
            echo '    <title>Redirecting to Mel Vocal Coaching Berlin</title>' >> _site/MelVocalcoachingbBerlin/MelVocalcoachingbBerlin/index.html
            echo '  </head>' >> _site/MelVocalcoachingbBerlin/MelVocalcoachingbBerlin/index.html
            echo '  <body>' >> _site/MelVocalcoachingbBerlin/MelVocalcoachingbBerlin/index.html
            echo '    <p>Redirecting to <a href="/MelVocalcoachingbBerlin/">Mel Vocal Coaching Berlin</a>...</p>' >> _site/MelVocalcoachingbBerlin/MelVocalcoachingbBerlin/index.html
            echo '  </body>' >> _site/MelVocalcoachingbBerlin/MelVocalcoachingbBerlin/index.html
            echo '</html>' >> _site/MelVocalcoachingbBerlin/MelVocalcoachingbBerlin/index.html
          fi
          
          # List all files for debugging
          echo "Files in _site directory:"
          find _site -type f | grep -v "node_modules" | sort
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: '_site'
          
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4 