name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Create static site
        run: |
          mkdir -p site
          cp -r public/* site/
          touch site/.nojekyll
          # Create simple index.html if it doesn't exist
          if [ ! -f site/index.html ]; then
            cat > site/index.html << 'EOL'
            <!DOCTYPE html>
            <html>
              <head>
                <meta charset="UTF-8">
                <meta http-equiv="refresh" content="0;url=/MelVocalcoachingbBerlin/">
                <title>Redirect to Mel Vocal Coaching Berlin</title>
              </head>
              <body>
                <p>Redirecting to <a href="/MelVocalcoachingbBerlin/">Mel Vocal Coaching Berlin</a>...</p>
              </body>
            </html>
            EOL
          fi

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: site
          branch: gh-pages 